services:
  web:
    build: ./app     #read Dockerfile in this directory
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: kartoza/postgis
    volumes:
      - ./pg/postgres_data:/var/lib/postgresql/:delegated
    environment:
      - POSTGRES_USER=django_webgis
      - POSTGRES_PASSWORD=django_webgis
      - POSTGRES_DB=django_webgis_dev
volumes:
  postgres_data:
